language: node_js
dist: trusty
sudo: false

node_js:
- "8"

install:
- npm install -g truffle ethereumjs-testrpc solium
- npm install
- truffle install

script:
- testrpc &> /dev/null & npm test
- npm run lint